name: advent_of_code
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  http: ^0.13.4
  rxdart: ^0.27.3
  scidart: ^0.0.2-dev.6
  b: ^0.1.1+1
  collection: ^1.15.0
  compute: ^1.0.2

dev_dependencies:
  lints: ^1.0.0
  dotenv: ^3.0.0
